services:
  keycloak:
    image: quay.io/keycloak/keycloak:23.0
    container_name: p4u_keycloak
    environment:
      KC_DB: mysql
      KC_DB_URL: jdbc:mysql://host.docker.internal:3306/keycloak
      KC_DB_USERNAME: root
      KC_DB_PASSWORD: root@123
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8180
      KC_HTTP_ENABLED: true
      KC_HTTP_PORT: 8180
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8180:8180"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: start-dev

