export type InvoiceItem = {
  name: string;
  qty: number;
  unitPrice: number;
  totalPrice: number;
};

export type InvoiceOrder = {
  id: string;
  createdAt?: string;
  status?: string;
  totalAmount?: number;
  customerName?: string;
  paymentRefId?: string;
};

function escapeHtml(value: unknown): string {
  const str = String(value ?? "");
  return str
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

function inr(value: number): string {
  return `₹${Number(value || 0).toFixed(2)}`;
}

export function downloadOrderInvoice(order: InvoiceOrder, items: InvoiceItem[], invoiceTitle = "Invoice"): void {
  if (typeof window === "undefined" || !items.length) return;
  const rows = items
    .map(
      (item, idx) => `
      <tr>
        <td>${idx + 1}</td>
        <td>${escapeHtml(item.name)}</td>
        <td>${item.qty}</td>
        <td>${inr(item.unitPrice)}</td>
        <td>${inr(item.totalPrice)}</td>
      </tr>`,
    )
    .join("");

  const computedTotal = items.reduce((sum, item) => sum + Number(item.totalPrice || 0), 0);
  const finalTotal = Number(order.totalAmount ?? computedTotal);
  const createdAt = order.createdAt ? new Date(order.createdAt).toLocaleString() : "—";

  const html = `<!doctype html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>${escapeHtml(invoiceTitle)}</title>
    <style>
      body { font-family: Arial, sans-serif; margin: 24px; color: #1f2937; }
      .head { display:flex; justify-content:space-between; margin-bottom: 16px; }
      .title { font-size: 20px; font-weight: 700; }
      .muted { color:#6b7280; font-size:12px; }
      table { width:100%; border-collapse: collapse; margin-top: 12px; }
      th, td { border:1px solid #e5e7eb; padding:8px; font-size: 12px; text-align:left; }
      th { background:#f9fafb; }
      .total { margin-top: 12px; text-align:right; font-size: 14px; font-weight: 700; }
    </style>
  </head>
  <body>
    <div class="head">
      <div>
        <div class="title">${escapeHtml(invoiceTitle)}</div>
        <div class="muted">Order ID: ${escapeHtml(order.id)}</div>
        <div class="muted">Date: ${escapeHtml(createdAt)}</div>
        <div class="muted">Status: ${escapeHtml(order.status || "—")}</div>
        <div class="muted">Payment Ref: ${escapeHtml(order.paymentRefId || "—")}</div>
      </div>
      <div class="muted">Generated by P4U</div>
    </div>
    <table>
      <thead>
        <tr>
          <th>#</th>
          <th>Product</th>
          <th>Qty</th>
          <th>Unit Price</th>
          <th>Total</th>
        </tr>
      </thead>
      <tbody>${rows}</tbody>
    </table>
    <div class="total">Grand Total: ${inr(finalTotal)}</div>
  </body>
</html>`;

  const blob = new Blob([html], { type: "text/html;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `${invoiceTitle.replace(/\s+/g, "_")}_${String(order.id).slice(0, 12)}.html`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
